### PR TITLE
Add a function: when using add-xp, if the user has enough xp to rank up after the xp is added, the user automatically ranks up.

### PR DESCRIPTION
**Pull request by brandoge91**
the title says it all.

i am going to make this a configurable thing. just gotta commit one more time and this pr should be complete

### CODE REVIEW

**Comment by brandoge91** [comment]
ok fixed stuff lol (also made it a option in config.ts)

**Comment by yogurtsyum** [comment]
Will test this today.

**Comment by brandoge91** [comment]
awesome. feel free to make any changes. i did some small testing and it seemed fine.

**Comment by yogurtsyum** [comment]
I will make a few changes shortly before merging this branch with master, but this looks good for now.

**Pull request merged**
