### PR TITLE
Add group-ban support

### PR DESCRIPTION
**Pull request by zachariapopcorn**
As the title suggests, this PR adds the ability for Qbot to "group ban" people, which basically just bans someone from joining the group again

I did test this and it worked for me, but if they are any bugs/problems, please comment

Thanks for reading, have a good day

### CODE REVIEW

**Comment by Oji0721** [comment]
You need to be in the group to ungroupban the member can you fix it?

**Comment by Oji0721** [comment]
https://gyazo.com/6b27e76376ae67da95438ef49ec91ab2 The picture link in the bug above ^^^

**Comment by zachariapopcorn** [comment]
Should be fixed, can you try again?

**Review by yogurtsyum — APPROVED** [review]
LGTM! Will push this in our next update.

**Comment by Oji0721** [comment]
Add this it will so helpful to me getAlreadyBannedEmbed and getAlreadyUnbannedEmbed all ranking command have this. Like getAlreadySuspendEmbed.

**Pull request merged**
