### PR TITLE
Add multi-role support for permissions

### PR DESCRIPTION
**Pull request by zachariapopcorn**
This PR, as the title suggests, allows for multiple roles to be added as required roles for the permission system

I did test this with the permission ``permissions.all`` and some commands, like shout via ``permissions.shout``

If there are any bugs that I didn't catch while testing, please do comment and I'll try to fix them

### CODE REVIEW

**Comment by yogurtsyum** [comment]
I think I would rather use the correct system and just map through permissions in the command files.

**Comment by zachariapopcorn** [comment]
What do you mean by this? If you mean like adding code to iterate through permissions in **every** command file, won't it just be more annoying to make new commands (and plugins for plugin developers) in the future, knowing that it would be required to have to copy-n-paste the code? I tried to make this implementation be global, but simple, thus why I only changed the checkPermissions function

**Comment by yogurtsyum** [comment]
We can use the checkPermissions function I guess.

**Comment by yogurtsyum** [comment]
I'm actually going to rewrite this because it doesn't use arrays and the code doesn't really match our styling.

**Comment by zachariapopcorn** [comment]
Oh, alright

**Comment by yogurtsyum** [comment]
Thanks for the PR anyways though.

**Pull request merged**
