### PR TITLE
Add Reason for Bans to Database

### PR DESCRIPTION
**Pull request by UnknownPerson3420**
When a user is group banned, the reason is currently only being logged in an embed. This pull requests adds the reason to MongoDB and will return the reason for the ban when /info is run.

### CODE REVIEW

**Comment by UnknownPerson3420** [comment]
Added API support, so /user will now return reasonForBan as well.

**Comment by UnknownPerson3420** [comment]
**Added to this PR:**

I added a change to the log for the XP API. This will allow people to see the target of the xp when it is run. (Useful for in-game-ranking)

**Comment by yogurtsyum** [comment]
I feel like this PR is slightly incomplete, having reasons persist solely for bans sounds like it should be part of a bigger feature.

Due to this, I am unfortunately going to close this, but I appreciate the submission anyways as a suggestion for future updates.

**Comment by phyouthcenter1** [comment]
Interesting

**Pull request closed without merging**
