### PR TITLE
Added multiple Verification API Providers + QOL changes/bug fixes

### PR DESCRIPTION
**Pull request by astranger1k**
Added a configuration option to select a preferred API Provider
Currently supporting:
 - Bloxlink (Default - api.blox.link/v1/)
 - Rowifi (api.rowifi.link/v1/)
 - Rover (verify.eryn.io/api/)

Added a reference to the API used to fetch the user in /info

Added a .env.example file to show what Environment Variables to create

Corrected command registration behavior (random bug that cropped up)

Corrected a grammatical error in README.md

### Refer to commits for changes.

### CODE REVIEW

**Comment by yogurtsyum** [comment]
I like the idea behind this PR but I've noticed some consistency issues with the rest of the bot's code. I will look into it more later and see if it is easier to accept this one and then make the changes, or redo the system.

**Comment by Oji0721** [comment]
Good but if you ping someone its doesn’t work.

**Comment by zachariapopcorn** [comment]
@Oji0721 That's an invalid image? Try uploading it again for OP to see it haha

**Comment by Oji0721** [comment]
@zachariapopcorn https://gyazo.com/84992984e85f04a163db099ffe718f7d

**Comment by astranger1k** [comment]
> Good but if you ping someone its doesn’t work.
> 
> 

oddly enough, whenever I ran it before my changes it never worked anyway, regardless of the API used.

**Comment by Oji0721** [comment]
Okay.

**Comment by astranger1k** [comment]
@yogurtsyum What needs doing to this PR before it is a viable solution?

**Comment by yogurtsyum** [comment]
In the configuration, you don't have a system to disable verification checks like before.

**Comment by yogurtsyum** [comment]
I've reverted this PR for a few reasons.

1) The styling of how you coded this really doesn't match what we used in Qbot.
2) Some of the QOL changes seemed unnecessary and actually might have broken certain things.
3) It appears some other features related to verification checks were deleted.

Thanks for the PR anyways.

**Pull request merged**
