### PR TITLE
so i hate git (recreation of #101)

### PR DESCRIPTION
**Pull request by brandoge91**
lmao read the desc of #101

### CODE REVIEW

**Comment by Oji0721** [comment]
Is this need a api on?

**Comment by brandoge91** [comment]
yes. are you trying to use this as your main bot? i advise against it as it is incomplete and stuff like the quota does not work yet

**Comment by Oji0721** [comment]
So I need to use api and connect it to my game right?

**Comment by brandoge91** [comment]
yes, but i strongly advise against using this PR, as it is messy and currently unfinished.

**Comment by brandoge91** [comment]
now marking this as a draft--- 

lots of work needs to be done and will be done over the next few days to improve this

**Comment by yogurtsyum** [comment]
@brandoge91 When do you think this will be ready for review? Because I need to figure out if we are including this in 7.2 or the update after that.

**Comment by brandoge91** [comment]
hopefully by 1/10 (2 days), but maybe earlier

**Comment by brandoge91** [comment]
actually, this might be done in a few hours. i'm on a roll! the only thing i might need help with is testing.

**Comment by brandoge91** [comment]
this is done. you can review it whenever now

**Review by yogurtsyum — APPROVED** [review]
LGTM. I am going to make a few changes about how this integrates into the Qbot ecosystem, though. Mainly by removing the qbotActivity.rbxm file and encouraging you to submit it as a plugin instead.

This is because I would like to only package the API itself into Qbot, and for any use cases, those should be considered plugins.

**Comment by brandoge91** [comment]
okay. i understand where you are coming from. will be recreated as a plugin PR and a API PR here

**Comment by yogurtsyum** [comment]
Not sure if you need to close this PR... just remove that one file.

**Comment by brandoge91** [comment]
oh, i understand what you meant now lol!

**Comment by brandoge91** [comment]
should now be good to merge (if i understand what u meant)

**Comment by yogurtsyum** [comment]
Do you think it would be best if instead of having references to activity in the actual bot, we just had a plugin for adding XP when a user is online for certain intervals?

**Comment by brandoge91** [comment]
sure, but what would we do about the quota? would that be a plugin? or just make it check XP?

**Comment by yogurtsyum** [comment]
Not sure to be honest... we could have our initial launch not include the quota system, and just allow adding XP based on activity through a plugin.

**Comment by brandoge91** [comment]
okay. ill put the quota system on the backburner for later, and ill make ingame xp a plugin

**Comment by yogurtsyum** [comment]
My goal is to have Qbot at its core just be a ranking bot, and have the power to install more tools that allow it to be a full ranking service. I think if we just had XP be a type of points system, and then had a plugin for applying this with activity, that would be received really well. What do you think?

**Comment by brandoge91** [comment]
seems like a great idea. i will keep all this stuff if we figure out a way to implement the quota as a plugin later, or we want any of it. i understand the purpose of qbot and i understand it :)))

**Comment by yogurtsyum** [comment]
Alright, for now I will close this pull request, but I look forward to seeing your Roblox activity tracking game as a plugin soon.

**Pull request closed without merging**
